### ISSUE TITLE
Help! Updated English pages don't trigger updates on respective PO files.

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz_docs#121]
I've run a full check of the manual pages for correctness in commands' menu locations, since the big menu reorganization.
So translators should check to see which pages have changed, and update them.

Regarding that, I'm seeing that translation PO files are not getting automatically updated on RST changes, as it used to be the case, and I really don't know how to update them manually either, so I'm stuck here.
Any help would be appreciated. 🤔 
@shun-iwasawa ?

**Comment by shun-iwasawa** [comment]
> I'm seeing that translation PO files are not getting automatically updated on RST changes, as it used to be the case, and I really don't know how to update them manually either, so I'm stuck here.

I'm wondering how did you get the PO files automatically updated, since I only know the way to do it manually..

According to [the manual](https://github.com/opentoonz/opentoonz_docs/blob/master/CONTRIBUTING.md#internationalization-i18n-of-the-manual), you can update them by the following commands:
```
$ make gettext
$ sphinx-intl update -p build/gettext -l es
```

Please note that the first line is for extracting translatable messages into pot files and the second line will generate .po files (for Spanish page, in this case) based on them.

You can also refer to [the documentation of Sphinx](https://www.sphinx-doc.org/en/master/usage/advanced/intl.html) for details.

**Comment by gab3d** [comment]
@shun-iwasawa 
well... I don't know how it was working internally, but what I can say is that in the past (at least 1 year ago and back), every time I changed something in the original English manual (and I've changed lots and lots of things in almost every page), the corresponding .po files were updated to show the new strings.

Currently that is not happening anymore, and is a big trouble in maintaining the Manual translations updated, because translators have no way to know changes have been introduced. Previously, if you came across some text in English (while seeing one of the translated versions), you instantly knew there were new changes in those strings, and you could go and updated them, now changes are simply invisible.
🤷🏻‍♂️

**Comment by gab3d** [comment]
@shun-iwasawa 
No, sorry... in a year I completely forgot how I was doing it.
Now I could remember, and I did used Sphinx in my system to update the PO files. (Since that notebook was stolen and never installed it again in my new system, I had completely forgotten about it).
Sorry, and thanks for your patience and efforts! :smile_cat:
