### ISSUE TITLE
Style convention proposal: Bolding the first use of a new term/name

### ISSUE THREAD

**Issue by WolfInABowl** [opentoonz/opentoonz_docs#49]
What do you think about this, is this something that should be used?

**Comment by yehjaemin** [comment]
Would it be the first use in the page, or the first in the entire documentation?

**Comment by artisteacher** [comment]
I think this could be helpful - but could be hard to keep track of.

**Comment by gab3d** [comment]
To be honest I don't feel any strict rule is helping more than limiting us here.
I know the importance of maintaining a certain style throughout the documentation, but I know I'm currently using bold to:
- stress things that are important to keep warned of / are important in a certain context.
- to overall make the blocks of text easier to navegate with the eyes by having the posibility to quickly look at certain spots to see "if the text is describing something related to what I'm looking for/interested in right now".

Currently I use **bold** for things that are the name of a function/tool/option that's being described or is "part of the action" (when following instructions), and also *italic* to make some considerations stand out a little from the rest of the surrounding text.

An example:

> "Select the *links* where you want to insert a new effect, right-click any of them and choose **Insert FX** from the menu that opens, then select the effect you want to insert from the available submenus."

Here I put a slight highlight in the word *links*, to let the user know that one is an important detail, and the bold in the *Insert FX* command name, because its the center of the instructions being given.

I feel that if another ser of instructions above already used Insert FX in bold, and just by that reason I cannot make the command stand out here in this specific instruction, then the rule will be playing against the reader, by making the instructions more dull to read.
