### ISSUE TITLE
I've edited the Interface overview from the Toonz Harlequin Guide

### ISSUE THREAD

**Issue by Orphanlast** [opentoonz/opentoonz_docs#5]
I feel as though the translation for the Toonz Harlequin Guide is rather poor. So I've gone ahead and edited it. I've also replaced the usage of the words "Toonz Harlequin" with "OpenToonz". I've also changed "Edit Tool" to "Animate Tool", made it more comprehensive with more pictures. It's currently a file residing on my   computer in a Libre Office file. The last three paragraphs, however, I feel I don't have the expertise to really edit. So I suppose I can leave that for someone more computer savvy to to. 

The problem is, I have no idea how to take these screen captures and how to put them into this thing. 

I put in a bunch of screen captures. And I don't think I can even use them. If I could get some help with this, it'd be much appreciated.

I'm hoping I can make a video showing the workflow I've used, but I'm stuck at this point. Any help would be appreciated.

**Comment by shun-iwasawa** [comment]
@Orphanlast Thank you for your contribution. 
As commented in another issue, [odt2sphinx](https://pypi.python.org/pypi/odt2sphinx/) seems to be for converting Libre Office file to .rst file.
I'm still new to Sphinx, but putting the image seems to be described in [here](http://www.sphinx-doc.org/en/stable/rest.html#images).
For adding the video, I think embedding it from youtube would be fine. [Here](https://groups.google.com/forum/#!topic/sphinx-users/_z00m3zoRAY) are some ways to do so, by writing raw html or by introducing `sphinxcontrib.youtube` .

I understand that it would be quite tough for non-developer to do these work from scratch, so I'll try to convert harlequin's manual to .rst in order to start working based on them. Also I'll add more detailed instructions for contributing to this repository. I think I need a few week to complete it. Thank you for your patience.

**Comment by shun-iwasawa** [comment]
I converted all texts of Harlequin's manual to .rst and put into this repository.
The instructions for contributing will need more days.

**Comment by Orphanlast** [comment]
I appreciate it. I'll see about adding the pictures then. I want to show people how to do it.

If they know how, they'll make it, and they'll use it.

Thank you.
