### ISSUE TITLE
Please clarify "viewer" -vs- "work area"...

### ISSUE THREAD

**Issue by pnelson2** [opentoonz/opentoonz_docs#9]
We just had a long, complicated discussion in the OpenToonz community about what exactly is the distinction between **Viewer** and **Work Area** in OpenToonz 1.2.     The documentation has two different sections for these two things, but by the end of the discussion we decided they are really the same.

I think this should be clearer in the documentation.

For details of the confusion see: [ https://groups.google.com/forum/#!category-topic/opentoonz_en/general-discussion/rAbjZcRfXsY]( https://groups.google.com/forum/#!category-topic/opentoonz_en/general-discussion/rAbjZcRfXsY)

Thanks in advance.

**Comment by shun-iwasawa** [comment]
Thank you @pnelson2 for the post and detailed discussions done so far in the forum! 
Since we are still very small team, we really appreciate if you could modify & post a PR for this matter.
And if you are interested, we will also be willing to assign you a collaborator access which will enable you to merge modifications by yourself. Please post a request to the issue #4 .

**Comment by pnelson2** [comment]
Hi shun-iwasawa

I'm not familiar with your development protocol so I don't know what "modify and post a PR" means.     And I'm a complete OpenToonz Noob so I should not be trusted to make any changes in the documentation yet.

BTW, what is the official latest rev of the User Manual in English?   The latest I can find is 1.13 on https://opentoonz.readthedocs.io/en/latest/ but there are discrepancies in the description of the Function Editor and what I see on 1.21.    Why is the User Manual on a separate site from the code?  Is it managed by a different group in the project?

I'll be happy to help when I get more up-to-speed with OpenToonz but if I touch anything at this stage I'll break it.

Peter Nelson

----------------------------------------

**Comment by shun-iwasawa** [comment]
> I'm not familiar with your development protocol so I don't know what "modify and post a PR" means.     And I'm a complete OpenToonz Noob so I should not be trusted to make any changes in the documentation yet. 

"PR" stands for "Pull Request", one of the main features of GitHub. 
If you happen to be interested, there is a brief description of contribution process in [CONTRIBUTING.md](https://github.com/opentoonz/opentoonz_docs/blob/master/CONTRIBUTING.md) .

> BTW, what is the official latest rev of the User Manual in English?

[https://opentoonz.readthedocs.io/en/latest/](https://opentoonz.readthedocs.io/en/latest/) is the latest revision of the user manual.
The user manual is based on Toonz Harlequin 7.1. And unfortunately, it is not yet revised from the original due to a manpower shortage. Although many parts in the software overlap, some parts (like panel layout of Function Editor, as you pointed) had been modified and the manual has not been updated.

> Why is the User Manual on a separate site from the code?  Is it managed by a different group in the project?

In order to make update process of the user manual smoother, we decided to assign the collaborator access to wider circle of community members.
GitHub has no customizability in the collaborator access. We cannot restrict some collaborator to change the code while allowing him to modify the user manual, as long as both of them are in the same repository. So, separating them into two repositories was reasonable for us to manage the role of contributors.
